# Generated by Django 3.1.2 on 2020-10-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstName',
        ),
        migrations.DeleteModel(
            name='LastName',
        ),
        migrations.DeleteModel(
            name='StreetAddress',
        ),
    ]
